train:
  _target_: src.datasets.ASVspoofDataset
  protocol_path: ${oc.env:ASVSPOOF_ROOT,/kaggle/input/datasets/awsaf49/asvpoof-2019-dataset}/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt
  audio_dir: ${oc.env:ASVSPOOF_ROOT,/kaggle/input/datasets/awsaf49/asvpoof-2019-dataset}/LA/LA/ASVspoof2019_LA_train/flac
  shuffle_index: True
  instance_transforms: ${transforms.instance_transforms.train}

dev:
  _target_: src.datasets.ASVspoofDataset
  protocol_path: ${oc.env:ASVSPOOF_ROOT,/kaggle/input/datasets/awsaf49/asvpoof-2019-dataset}/LA/LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.dev.trl.txt
  audio_dir: ${oc.env:ASVSPOOF_ROOT,/kaggle/input/datasets/awsaf49/asvpoof-2019-dataset}/LA/LA/ASVspoof2019_LA_dev/flac
  shuffle_index: False
  instance_transforms: ${transforms.instance_transforms.inference}
