defaults:
  - model: lcnn
  - metrics: eer
  - datasets: asvspoof_eval
  - dataloader: main
  - transforms: asvspoof
  - _self_
inferencer:
  device_tensors: ["audio", "labels"]
  device: auto
  save_path: "asvspoof"
  seed: 1
  from_pretrained: "saved/model_best.pth"
